name: Commands Test
on: [push]

jobs:
    macOS:
        name: Run macOS
        runs-on: macos-latest
        steps:
            - name: Echo hello world
              run: echo 'hello world from macOS.'
    Ubuntu:
        name: Run Ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Echo hello world
              run: echo 'hello world from ubuntu.'
